### ISSUE TITLE
Connection failed: Invalid connector type: l2cap

### ISSUE THREAD

**Issue by software3daerospace** [kenjdavidson/react-native-bluetooth-classic#116]
Hello Ken,

What are the other CONNECTION_TYPE values other than "rfcomm"  for connect() function? 
From the documentation (https://kenjdavidson.com/react-native-bluetooth-classic/react-native/rn-bluetooth-device/)
its only specified about rfcomm. It would really help what are the values to be given for OBEX and L2CAP. if I give "obex" or "obex", then i get this error - `Connection failed: Invalid connector type: l2cap` or `Connection failed: Invalid connector type: l2cap`  respectively

**Comment by kenjdavidson** [comment]
Have you read the documentation?

There are no other types provided by default, only RFCOMM.  I redesigned the library to make it extendable.  You can write your own:
- DeviceAcceptor
- DeviceConnector
- DeviceConnection

and provide them to the Bluetooth module so that you can do anything you want, without having to re-write or modify the actual library itself.  

There are examples of doing so with the `ByteArrayDeviceConnectionImpl`.
