### ISSUE TITLE
Possibly outdated "Android minSdkVersion" info in README file for master branch

### ISSUE THREAD

**Issue by enatividad** [kenjdavidson/react-native-bluetooth-classic#130]
**Mobile Device Environment**
.

**Application Environment**
.

**Describe the bug**
I looked at the `build.gradle` file and saw `minSdkVersion 16`. However, the master branch README file still states that `1.60.x` branch require a minimum of Android 8.0 (sdk 26).

Is it correct to assume that the README file is outdated?

**To Reproduce**
.

**Expected behavior**
.

**Screenshots**
.

**Additional context**
.

**Comment by kenjdavidson** [comment]
No the Readme is correct, the fun of react native and Android versions.

Minsdk was left in there due to some of the android apis still being in use. I forget exactly why, I think there was an old issue when I first released that asked to put it back, so I complied.  I'm not entirely sure.

Are you have issues? Or just being nitpicky?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Emmanuel Natividad ***@***.***>
Sent: Thursday, September 2, 2021 10:49:58 PM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] Possibly outdated "Android minSdkVersion" info in README file for master branch (#130)


Mobile Device Environment
Provide a list of operating systems on which this issue is relevant.

  *   Device: [e.g. Android, iPhone6]
  *   OS: [e.g. API19, Nouget, iOS8.1]

Application Environment
Provide information about your development environment:

  *   React Native version: [e.g. v0.61.0]
  *   RN Bluetooth Classic version: [e.g. v0.10.3]

Describe the bug
I looked at the build.gradle file and saw minSdkVersion 16. However, the master branch README file still states that 1.60.x branch require a minimum of Android 8.0 (sdk 26).

Is it correct to assume that the README file is outdated?

To Reproduce
Steps to reproduce the behavior:

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Additional context
Add any other context about the problem here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenjdavidson%2Freact-native-bluetooth-classic%2Fissues%2F130&data=04%7C01%7C%7Cc98a1219fdae40126bee08d96e858554%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637662342007232906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=umdW3UOBuwVMOdh%2BLT5zPBawWuobGG9%2Fa6xvjcaLgEE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPMJL3M4GWWFRVKHQZXAQTUAAZVNANCNFSM5DKZLZ7Q&data=04%7C01%7C%7Cc98a1219fdae40126bee08d96e858554%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637662342007242865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZkfYAaGbqcHAkdmlmJzHGsjLqPYMaE2TEkaEn22xyg0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc98a1219fdae40126bee08d96e858554%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637662342007242865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jnamlx21EiTh6tbnpJV2YAb1nJqJ9vr3YVx6rN4MvMc%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc98a1219fdae40126bee08d96e858554%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637662342007252858%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rOqTvyzfEJ0UodDCB6zb%2FOA1DnbbyfAi1i0u71idRrQ%3D&reserved=0>.
