### ISSUE TITLE
Is there a way for us not to use setInterval() to read the data? Continuously reading from device without setInterval()

### ISSUE THREAD

**Issue by sunny812546** [kenjdavidson/react-native-bluetooth-classic#140]
**Similar To This**

BluetoothSerial.withDelimiter('\r').then(() => {
      Promise.all([
        BluetoothSerial.isEnabled(),
        BluetoothSerial.list(),
      ]).then(values => {
        const [isEnabled, devices] = values;
        ...
      });
      BluetoothSerial.on('read', data => {
        console.log(`DATA FROM BLUETOOTH: ${data.data}`);
     });
});

**Comment by kenjdavidson** [comment]
I don't understand the question. Is there a problem with the on read listener? It's been working for me and others that I'm aware of.

If you can't get it working I suggest reading the docs and looking at the sample app.

Or are you saying there's a bug with it?

If there is a bug you need to provide way more details on what and how to replicate.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Sunny Patel ***@***.***>
Sent: Wednesday, November 24, 2021 7:36:26 AM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] Is there a way for us not to use setInterval() to read the data? Continuously reading from device without setInterval() (Issue #140)


Similar To This

BluetoothSerial.withDelimiter('\r').then(() => {
Promise.all([
BluetoothSerial.isEnabled(),
BluetoothSerial.list(),
]).then(values => {
const [isEnabled, devices] = values;
...
});
BluetoothSerial.on('read', data => {
console.log(DATA FROM BLUETOOTH: ${data.data});
});
});

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenjdavidson%2Freact-native-bluetooth-classic%2Fissues%2F140&data=04%7C01%7C%7C165222a6b46a47d1082308d9af470891%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637733541883673232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5%2ByZTPhwpAROq4rkVi8QpG9XzzVCWCM4dFDSgG0LCkI%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPMJLYD3NTITQ6E72QXBO3UNTL4VANCNFSM5IV6YD7A&data=04%7C01%7C%7C165222a6b46a47d1082308d9af470891%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637733541883683229%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KF7sA6JyWo07yMuC5DtSj26Rde5RgHQf7y217lAHq14%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C165222a6b46a47d1082308d9af470891%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637733541883683229%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S%2FJibKW4SD0FPuqLzObK8whoPHIf8nAc%2BXfJT3EwzUc%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C165222a6b46a47d1082308d9af470891%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637733541883693215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VU8M5mFfXs1GTUb%2FgSqrnN49JehpeWmhBxkqwLM1UAk%3D&reserved=0>.

**Comment by sunny812546** [comment]
First of all, I am impressed with this library. Great work, great effort.. 🔥

I just want to know how to read continuous read from a Bluetooth classic device using this library.

Because I used setInterval() for continuous Reading.

Is there any better way to continuously read data from the device via Bluetooth?

**Comment by kenjdavidson** [comment]
Yes, it's in the doc:

https://kenjdavidson.com/react-native-bluetooth-classic/react-native/rn-bluetooth-device/#ondatareceived

And the sample application:

https://github.com/kenjdavidson/react-native-bluetooth-classic-apps/blob/1cba89aaa1181998dbcab7a9549a88a9bb5071a1/BluetoothClassicExample/src/connection/ConnectionScreen.js#L140

**Comment by kenjdavidson** [comment]
Also, thank you.

**Comment by sunny812546** [comment]
Now, I am getting continuous read and it is very fast. Thanks a lot.❤❤❤
