### ISSUE TITLE
RNBluetoothClassic object is null 

### ISSUE THREAD

**Issue by DamianoBarone** [kenjdavidson/react-native-bluetooth-classic#167]
**Mobile Device Environment**
Android tablet galaxy s7+

**Application Environment**
Provide information about your development environment:
- React Native version: [e.g. v5.0.1]
- RN Bluetooth Classic version: [latest, download today]
- Expo (latest)
- npm 8.5.0
- running on MacBook Pro 11.62

**Describe the bug**
I can't use any method of RNBluetoothClassic, it give me an error that the object is null
Error: [TypeError: null is not an object (evaluating 'this._nativeModule.isBluetoothEnabled')]
I have imported
 import RNBluetoothClassic from 'react-native-bluetooth-classic';
async function btList() {
  try {
    let devices = await RNBluetoothClassic.isBluetoothEnabled();
  } catch (err) {
    console.log('Error:', err);
  }
}
btList is called in the useEffect()  (I'm using function component)
I've installed the react-native-bluetooth-classic with npm and yarn, I have also tried the expo plugin. But same error.
In the main application.jave
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new MainReactPackage());
      packages.add(new ReactToolbarPackage());
      packages.add(new RNBluetoothClassicPackage());
      return packages;
    }
I added this, I tried different setting, but same  problem.

**To Reproduce**
Steps to reproduce the behaviour:
If I follow step by step your guide I'm ending in this problem

**Expected behaviour**
I should be able to call all the methods of RNBluetoothClassic
**Screenshots**

**Additional context**
your job is incredible, I'm sad that I have to annoying you. 
I have also create this post 
https://stackoverflow.com/questions/71104150/null-is-not-an-object-evaluating-this-nativemodule-isbluetoothenabled-in-re

**Comment by kenjdavidson** [comment]
You need to use an extra library to get this working with expo. I didn't write it but it was confirmed working by the author. Look in tee documentation for the expo section and maybe open an issue in his.

I don't use expo, and Bluetooth originally didn't work with expo, so I can't help much.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Damiano Barone ***@***.***>
Sent: Sunday, February 13, 2022 7:13:00 PM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] RNBluetoothClassic object is null (Issue #167)


Mobile Device Environment
Android tablet galaxy s7+

Application Environment
Provide information about your development environment:

  *   React Native version: [e.g. v5.0.1]
  *   RN Bluetooth Classic version: [latest, download today]
  *   Expo (latest)
  *   npm 8.5.0
  *   running on MacBook Pro 11.62

Describe the bug
I can't use any method of RNBluetoothClassic, it give me an error that the object is null
Error: [TypeError: null is not an object (evaluating 'this._nativeModule.isBluetoothEnabled')]
I have imported
import RNBluetoothClassic from 'react-native-bluetooth-classic';
async function btList() {
try {
let devices = await RNBluetoothClassic.isBluetoothEnabled();
} catch (err) {
console.log('Error:', err);
}
}
btList is called in the useEffect() (I'm using function component)
I've installed the react-native-bluetooth-classic with npm and yarn, I have also tried the expo plugin. But same error.
In the main application.jave
@OverRide<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOverRide&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MsUPiw%2FCjmnE1sKvkwbmjPN2FT31%2BY6pA4pWMmSuSBo%3D&reserved=0>
protected List getPackages() {
@SuppressWarnings<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSuppressWarnings&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fKMogMq%2FFty9QwFkaFF4P7MIlfidrbIMmG9Fb3iJp%2Fc%3D&reserved=0>("UnnecessaryLocalVariable")
List packages = new PackageList(this).getPackages();
// Packages that cannot be autolinked yet can be added manually here, for example:
// packages.add(new MyReactNativePackage());
packages.add(new MainReactPackage());
packages.add(new ReactToolbarPackage());
packages.add(new RNBluetoothClassicPackage());
return packages;
}
I added this, I tried different setting, but same problem.

To Reproduce
Steps to reproduce the behaviour:
If I follow step by step your guide I'm ending in this problem

Expected behaviour
I should be able to call all the methods of RNBluetoothClassic
Screenshots
If applicable, add screenshots to help explain your problem.

Additional context
your job is incredible, I'm sad that I have to annoying you.
I have also create this post
https://stackoverflow.com/questions/71104150/null-is-not-an-object-evaluating-this-nativemodule-isbluetoothenabled-in-re<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F71104150%2Fnull-is-not-an-object-evaluating-this-nativemodule-isbluetoothenabled-in-re&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8aMBwOt0wnAuGixZqrncRFOE%2B2WGBohqYX0KED96LBE%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenjdavidson%2Freact-native-bluetooth-classic%2Fissues%2F167&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1TOqo3gO1vJKHrA2y7uuyF4xxHg4FuTwtaBxpSXBRwM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPMJL67GXYVAEDOZ7RG6DLU3BCIZANCNFSM5OJ5Q66A&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y1Isy%2FVHkRTdXtT138vtapqeEGasPlMEBHDtT2f3blY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Pq%2FzXszij5vPm8aAM5S9ALIIEp0oc1n6%2Bc0zPBPMcG4%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5837666edb084c89ecd208d9ef4ec2e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803943816930253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h%2BhTZZx4uLeSyZSWdvMfiuWi%2Fn4EuT1ZviTp0eBo3G0%3D&reserved=0>.

**Comment by DamianoBarone** [comment]
thank you very much for the quick answer.
Honestly I'm not dependent of EXPO, so I can choose anything else. Important is that bluetooth is working.
What do you use or recommend for you API?

**Comment by kenjdavidson** [comment]
I just use the regular react native app. Expo wasn't good when I started the Bluetooth thing so I never bothered. It should work not with the provided library.

https://github.com/kenjdavidson/react-native-bluetooth-classic/issues/124

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by DamianoBarone** [comment]
Ok thank you very much!!
