### ISSUE TITLE
Doubt about MFi

### ISSUE THREAD

**Issue by Luanfv** [kenjdavidson/react-native-bluetooth-classic#170]
Hello, I'm working on an application that communicates with a raspberry via bluetooth, this raspberry product is being developed by another company. That said, I'm having trouble making bluetooth communication through iOS, I saw several issues commenting on the MFi, but I would like to know if it's possible to at least do tests with MFi package tests (found on the internet) before asking the company sign up for apple, because today I'm not even able to list the paired devices.

Note: the app is already perfect on android

**Comment by kenjdavidson** [comment]
If you can find an MFi device with free protocol strings, then yes you can test thing.  From what I’ve seen people experiement with, there are:

  *   Barcode scanners
  *   Printers
  *   Lego has a set that has them

You’ll have to search around though, I don’t know the specifics.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Luan França ***@***.***>
Sent: Tuesday, February 22, 2022 4:02 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] Doubt about MFi (Issue #170)


Hello, I'm working on an application that communicates with a raspberry via bluetooth, this raspberry product is being developed by another company. That said, I'm having trouble making bluetooth communication through iOS, I saw several issues commenting on the MFi, but I would like to know if it's possible to at least do tests with MFi package tests (found on the internet) before asking the company sign up for apple, because today I'm not even able to list the paired devices.

Note: the app is already perfect on android

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenjdavidson%2Freact-native-bluetooth-classic%2Fissues%2F170&data=04%7C01%7C%7C2e7b98a274624e6110aa08d9f6469507%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637811605272266363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Feil3zhGMmhH8qlge8%2BXmD0EJTqx6QjqCSAngGVojR4%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPMJL4XUL2FZW4YDYBRRQTU4P2UZANCNFSM5PCQMVFQ&data=04%7C01%7C%7C2e7b98a274624e6110aa08d9f6469507%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637811605272266363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HTfcqwSJ2dWspE%2F%2B%2FxpibS78LkA54K0Q%2FVh2zAVGRZ4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2e7b98a274624e6110aa08d9f6469507%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637811605272266363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pWmWc0%2FA%2FqGCirO1BC3D2uahoQYhwoo%2FBTf9qY4NsJk%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2e7b98a274624e6110aa08d9f6469507%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637811605272266363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Aky21ZC25vp9xPqFMS7PrysyenfwnDdYdKzuayE7RYg%3D&reserved=0>.

**Comment by Luanfv** [comment]
when I run the getBondedDevices function on iOS it returns an empty object, do you know what it can be?

**Comment by Luanfv** [comment]
Correct me if I'm wrong, please, to perform this function I need the app and the device I want to connect to have the same package to work, right? If so, is there any other way to establish a connection without having to register this package on the device I want to connect to?

reference: https://github.com/kenjdavidson/react-native-bluetooth-classic/issues/82#issuecomment-799614528

**Comment by kenjdavidson** [comment]
If you're working with IOS the call to `getBondedDevices` will only return a list of paired devices for which you have the correct protocol Strings.   So, if you have a device paired it will show up in the IOS System list of devices, but if you do not have the correct protocol string, you will not see that in the `getBondedDevices` list.  This is working as defined by the `ExternalAccessory` documentation.

I don't know what you mean by **need the app and device to have the same package**?  You mean **protocol string**?

**Comment by Luanfv** [comment]
I'm aware of very low iOS, so I apologize for the difficulty of expressing myself, but yes, I'm referring to ExternalAccessory, is there any way to establish a connection without them sharing the same?

**Comment by kenjdavidson** [comment]
No, that's the whole purpose of the ExternalAccessory and MFi requirements.

**Comment by Luanfv** [comment]
If i ask the people who developed the raspberry part to add the test mfi i found on the internet, would it work? thinking about tests, of course

**Comment by kenjdavidson** [comment]
They can't just add a random protocol string.  They need to pay a bunch of money and sign a bunch of NDA's and go through a bunch of testing to get their device on the MFi program.  If they are willing to go through that process, and provide you with this string, then yes you will be able to communicate.

When working with the MFi program, for every version of the application you release, you need to reach out to that company and have them submit a new request to the MFi program stating that your new application version is still permitted to use those protocols.

The whole process is crazy annoying, and I would suggest you move to BLE if it's remotely possible.

**Comment by kenjdavidson** [comment]
For testing, once they are on the MFi list, you can use their protocol strings without having your application validated by Apple.  But once you're ready to go live, you have to jump through all the hoops.

**Comment by Luanfv** [comment]
what is the difference between bluetooth classic and ble?

**Comment by kenjdavidson** [comment]
https://medium.com/@akash.kandhare/bluetooth-vs-bluetooth-low-energy-whats-the-difference-74687afcedb1#:~:text=Just%20like%20Bluetooth%2C%20BLE%20operates,Bluetooth%20which%20would%20take%20~100ms.

**Comment by kenjdavidson** [comment]
With regards to IOS, BLE doesn't use the ExternalAccessory library, it uses CoreBLuetooth, which doesn't require any of the MFi nonesense.
