### ISSUE TITLE
iOS Bluetooth classic device list get always empty

### ISSUE THREAD

**Issue by hupptechnologies** [kenjdavidson/react-native-bluetooth-classic#201]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: iPhone11
- OS: 15

**Application Environment**
Provide information about your development environment:
- React Native version: 0.63.4
- RN Bluetooth Classic version: latest

**Describe the bug**
When i try to scan or try to find the bluetooth connected device using the **getConnectedDevices** or **getBondedDevices** method then i am always getting empty array even the bluetooth device is connected.

**To Reproduce**
- [Just run your example app and see](https://github.com/kenjdavidson/react-native-bluetooth-classic-apps)

**Expected behavior**
- It should be get the connected device list via bluetooth.

**Screenshots**

**Additional context**

**Comment by kenjdavidson** [comment]
What are the mfi protocol strings you're using? And what device are you expecting?

Ios Is special and doenst just let you see all devices.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Hupp Technologies ***@***.***>
Sent: Monday, September 26, 2022 5:52:41 AM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] iOS Bluetooth classic device list get always empty (Issue #201)


Mobile Device Environment
Provide a list of operating systems on which this issue is relevant.

  *   Device: iPhone11
  *   OS: 15

Application Environment
Provide information about your development environment:

  *   React Native version: 0.63.4
  *   RN Bluetooth Classic version: latest

Describe the bug
When i try to scan or try to find the bluetooth connected device using the getConnectedDevices or getBondedDevices method then i am always getting empty array even the bluetooth device is connected.

To Reproduce
Steps to reproduce the behavior:

  *   Just run your example app and see<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenjdavidson%2Freact-native-bluetooth-classic-apps&data=05%7C01%7C%7C70691f316ead4dd0bbf808da9fa4dae2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637997827639757372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xIvrzDcULnEAYkgGMUt8LUSLhIC9JG7HzOP4jBhS1Qs%3D&reserved=0>

Expected behavior

  *   It should be get the connected device list via bluetooth.

Screenshots
If applicable, add screenshots to help explain your problem.

Additional context
Add any other context about the problem here.
