### ISSUE TITLE
RSSI always empty

### ISSUE THREAD

**Issue by avanmalleghem** [kenjdavidson/react-native-bluetooth-classic#335]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: Android
- OS: Android 13

**Describe the bug**
RSSI is always empty when checking it on a connected device.

**Expected behavior**
I would like to get the RSSI value.

**Comment by kenjdavidson** [comment]
From my understanding this is not possible.  The rssi is only populated from the Bluetooth adapter during search/discovery. I don't believe it's available otherwise.

If you feel otherwise, feel free to post a pr. But I think this was asked and confirmed a while ago.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Antoine Van Malleghem ***@***.***>
Sent: Wednesday, July 31, 2024 11:59:17 AM
To: kenjdavidson/react-native-bluetooth-classic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kenjdavidson/react-native-bluetooth-classic] RSSI always empty (Issue #335)


Mobile Device Environment
Provide a list of operating systems on which this issue is relevant.

  *   Device: Android
  *   OS: Android 13

Describe the bug
RSSI is always empty when checking it on a connected device.

Expected behavior
I would like to get the RSSI value.

**Comment by avanmalleghem** [comment]
Yep, I saw this thread aswell : https://github.com/kenjdavidson/react-native-bluetooth-classic/issues/90
It seems complicated on Android and... Impossible on IOS. Too bad... Thanks for the answer !
